ARG VARIANT="8.0-bookworm-slim"
FROM mcr.microsoft.com/dotnet/sdk:${VARIANT}

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends postgresql-client-common postgresql-client

# Quitamos la instalación de dotnet-ef que falla
# RUN dotnet tool install --global dotnet-ef
# ENV PATH=$PATH:/root/.dotnet/tools

RUN dotnet dev-certs https

WORKDIR /source
COPY . .
ENTRYPOINT ["tail", "-f", "/dev/null"]
