require 'yaml'
creds = YAML.load_file('variables.yml') rescue { 'username' => 'usuario_default', 'password' => 'contraseña_default' }

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20250126.1"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512 # 512MB de RAM
    vb.cpus   = 1   # 1 CPU
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt upgrade -y
    sudo apt-get install -y ca-certificates curl
    sudo install -m 0755 -d /etc/apt/keyrings
    sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    useradd -m -s /bin/bash -G sudo #{creds['username']}
    echo "#{creds['username']}:#{creds['password']}" | chpasswd
    sudo bash -c "echo '#{creds['username']} ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/#{creds['username']}"
    echo "Usuario #{creds['username']} pass #{creds['password']}"
  SHELL

  config.vm.hostname = "M11-EAC4-debian12"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.56.101"

end
